modLoader="javafml"
loaderVersion="[40,)"
license="the mod's copyright goes to Gyisti Production. Do not Copy all of Gyisti Production's projects."

[[mods]]
modId="encx"
version="1.0.1"
displayName="Encodem X"
credits="created using MCreator"
displayURL="https://gyisti.github.io/"
logoFile="logo.png"
authors="Gyisti, MCreator"
description='''
Encodem X is an Element Mod.
'''

[[dependencies.encx]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




